import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Saptarshi',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Apple",
      slug: "apple",
      image: "https://freepngimg.com/thumb/apple/9-apple-png-image-thumb.png",
      price: 35,
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      category: "Fruits",
    },
    {
      name: "Banana",
      slug: "banana",
      image: "https://freepngimg.com/thumb/banana/26-banana-png-image-bananas-picture-download-thumb.png",
      price: 12,
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      category: "Fruits",
    },
    {
      name: "Grapes",
      slug: "grapes",
      image: "https://freepngimg.com/thumb/grape/4-grape-png-image-download-picture-thumb.png",
      price: 45,
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      category: "Fruits",
    },
    {
      name: "Pineapple",
      slug: "pineapple",
      image: "https://freepngimg.com/thumb/pineapple/5-pineapple-png-image-download-thumb.png",
      price: 200,
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      category: "Fruits",
    },
    {
      name: "Mango",
      slug: "mango",
      image: "https://freepngimg.com/thumb/mango/1-2-mango-png-thumb.png",
      price: 35,
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      category: "Fruits",
    },
    {
      name: "Water melon",
      slug: "watermelon",
      image: "https://freepngimg.com/thumb/watermelon/1-watermelon-png-image-thumb.png",
      price: 50,
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      category: "Fruits",
    },
    {
      name: "Cabbage",
      slug: "cabbage",
      image: "https://freepngimg.com/thumb/cabbage/6-cabbage-png-image-thumb.png",
      price: 30,
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      category: "vegetables",
    },
    {
      name: "Capsicum",
      slug: "capsicum",
      image: "https://www.nicepng.com/png/detail/52-525615_green-bell-pepper-png-green-capsicum-png.png",
      price: 35,
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      category: "vegetables"
    },
    {
      name: "Garlic",
      slug: "garlic",
      image: "https://www.freepngimg.com/thumb/garlic/2-2-garlic-transparent-thumb.png",
      price: 45,
      category: "vegetables",
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product"
    },
    {
      name: "Beetroot",
      slug: "beetroot",
      image: "https://pngimg.com/uploads/beet/beet_PNG28.png",
      price: 20,
      category: "vegetables",
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product"
    },
    {
      name: "Tomatoes",
      slug: "tomatoes",
      image: "https://png.pngtree.com/png-vector/20210529/ourmid/pngtree-tomato-food-gourmet-vegetables-png-image_3369387.jpg",
      price: 25,
      category: "vegetables",
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product"
    },
    {
      name: "Celeriac",
      slug: "celeriac",
      image: "https://w7.pngwing.com/pngs/252/146/png-transparent-celeriac-leaf-vegetable-food-celery-herbes-leaf-vegetable-food-plant-stem-thumbnail.png",
      price: 10,
      category: "vegetables",
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product"
    },
    {
      name: "Carrots",
      slug: "carrots",
      image: "https://www.bigbasket.com/media/uploads/p/l/10000200-5_1-fresho-tomato-hybrid.jpg",
      price: 60,
      category: "vegetables",
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product"
    },
    {
      name: "Onions",
      slug: "onions",
      image: "https://www.freepngimg.com/thumb/onion/10-red-onion-png-image-thumb.png",
      price: 89,
      category: "vegetables",
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product"
    },
    {
      name: "Coriander",
      slug: "coriander",
      image: "https://w7.pngwing.com/pngs/867/336/png-transparent-dish-herb-parsley-root-vegetable-food-vegetable-leaf-vegetable-dried-fruit-superfood-thumbnail.png",
      price: 18,
      category: "vegetables",
      brand: "Fresho",
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product"
    },
    {
      "name": "Brown Rice",
      "slug": "brown-rice",
      "image": "https://w7.pngwing.com/pngs/209/677/png-transparent-brown-rice-five-grains-cereal-food-rice-coarse-grains-brown-recipe-nutrition-thumbnail.png",
      "price": 30,
      "brand": "Fresho",
      "countInStock": 20,
      "rating": 4.0,
      "numReviews": 10,
      "description": "high quality product",
      "category": "foodgrain"
    },
    {
      "name": "Coffee Bean",
      "slug": "coffee-bean",
      "image": "https://w7.pngwing.com/pngs/187/621/png-transparent-coffee-bean-lot-congee-black-rice-five-grains-food-delicious-bowl-of-black-rice-black-hair-black-white-whole-grain-thumbnail.png",
      "price": 120,
      "brand": "Fresho",
      "countInStock": 20,
      "rating": 4.0,
      "numReviews": 10,
      "description": "high quality product",
      "category": "foodgrain"
    },
    {
      "name": "Pomegranate Bean",
      "slug": "pomegranate-bean",
      "image": "https://img.favpng.com/0/23/0/cranberry-pomegranate-auglis-vegetable-fruit-png-favpng-1tE1AyCxS7B5SCY7FLudZEXEi_t.jpg",
      "price": 145,
      "brand": "Fresho",
      "countInStock": 20,
      "rating": 4.0,
      "numReviews": 10,
      "description": "high quality product",
      "category": "foodgrain"
    },
    {
      "name": "Whole Grains",
      "slug": "whole-grains",
      "image": "https://e7.pngegg.com/pngimages/703/631/png-clipart-cereal-rice-food-whole-grain-wheat-whole-grains-nutrition-oat-thumbnail.png",
      "price": 45,
      "brand": "Fresho",
      "countInStock": 20,
      "rating": 4.0,
      "numReviews": 10,
      "description": "high quality product",
      "category": "foodgrain"
    },
    {
      "name": "Oats Whole Grains",
      "slug": "oats-whole-grains",
      "image": "https://e7.pngegg.com/pngimages/887/662/png-clipart-cereals-rolled-oats-cereal-whole-grain-oatmeal-oatmeal-food-oat-thumbnail.png",
      "price": 99,
      "brand": "Fresho",
      "countInStock": 20,
      "rating": 4.0,
      "numReviews": 10,
      "description": "high quality product",
      "category": "foodgrain"
    },
    {
      "name": "Peanut Grains",
      "slug": "peanut-grains",
      "image": "https://png.pngtree.com/png-clipart/20220124/ourmid/pngtree-peanut-grains-png-transparent-material-png-image_4254013.png",
      "price": 68,
      "brand": "Fresho",
      "countInStock": 20,
      "rating": 4.0,
      "numReviews": 10,
      "description": "Best quality peanut in the world",
      "category": "foodgrain"
    },
    {
      "name": "Amul milk",
      "slug": "amul-milk",
      "image": "https://w7.pngwing.com/pngs/998/299/png-transparent-milk-bag-buttermilk-amul-toned-milk-milk-cream-textile-material-thumbnail.png",
      "price": 30,
      "brand": "Amul",
      "countInStock": 20,
      "rating": 4.0,
      "numReviews": 10,
      "description": "Amul milk is a high-quality milk product that is made from fresh, healthy cows. It is a good source of protein, calcium, and other nutrients.",
      "category": "Dairy and Bakery"
    },
    {
      "name": "Milky Mist Curd",
      "slug": "milky-mist-curd",
      "image": "https://www.bigbasket.com/media/uploads/p/s/40003162_5-milky-mist-curd-farm-fresh.jpg",
      "price": 15,
      "brand": "Milky Mist",
      "countInStock": 20,
      "rating": 4.5,
      "numReviews": 50,
      "description": "Milky Mist Curd is a delicious and refreshing curd that is made from fresh, full-fat milk. It is a good source of protein and calcium.",
      "category": "Dairy and Bakery"
    },
    {
      "name": "Amul Butter",
      "slug": "amul-butter",
      "image": "https://www.bigbasket.com/media/uploads/p/s/1204991_3-amul-butter-pasteurized.jpg",
      "price": 15,
      "brand": "Amul",
      "countInStock": 20,
      "rating": 4.0,
      "numReviews": 10,
      "description": "Amul Butter is a delicious and versatile butter that is made from fresh, cream. It is a good source of Vitamin A and D.",
      "category": "Dairy and Bakery"
    },
    {
      "name": "Brown Bread",
      "slug": "brown-bread",
      "image": "https://www.bigbasket.com/media/uploads/p/s/70001169_11-english-oven-bread-brown.jpg",
      "price": 31,
      "brand": "Britannia",
      "countInStock": 20,
      "rating": 4.3,
      "numReviews": 30,
      "description": "Brown Bread is a healthy and delicious bread that is made with whole wheat flour. It is a good source of fiber and protein.",
      "category": "Dairy and Bakery"
    },
    {
      "name": "Oat meal",
      "slug": "oat-meal",
      "image": "https://www.bigbasket.com/media/uploads/p/s/40219512_3-tasties-oatmeal-cookies-sugar-free.jpg",
      "price": 66,
      "brand": "Tasties",
      "countInStock": 20,
      "rating": 4.0,
      "numReviews": 10,
      "description": "Oat meal is a healthy and delicious breakfast cereal that is made from oats. It is a good source of fiber and protein.",
      "category": "Dairy and Bakery"
    }
  ]
};
export default data;
